#!/usr/bin/env python3
"""Train a small MLP on the host and export the weights as Rust consts (no_std).

Demonstrates the core project principle: train on the laptop (here with numpy), then run identical
inference inside seL4 with Rust and no std. We also export reference states (input→output)
to verify that Rust matches numpy (Software-in-the-Loop).

Usage:  python3 training/train_policy.py
Output: components/policy/src/weights.rs
"""
import os
import numpy as np

np.random.seed(7)  # deterministic (no free Date/random)

IN, HID, OUT = 8, 16, 4
N = 512        # training samples
EPOCHS = 4000
LR = 0.05


def relu(x):
    return np.maximum(x, 0.0)


def main():
    # Hidden teacher: generate structured target data from it.
    Wt = np.random.randn(IN, OUT).astype(np.float32) * 0.7
    X = np.random.randn(N, IN).astype(np.float32)
    Y = relu(X @ Wt).astype(np.float32)  # simple nonlinear target

    # Student: MLP with one hidden layer.
    W1 = (np.random.randn(HID, IN) * 0.3).astype(np.float32)
    b1 = np.zeros(HID, np.float32)
    W2 = (np.random.randn(OUT, HID) * 0.3).astype(np.float32)
    b2 = np.zeros(OUT, np.float32)

    # Simple SGD training (manual backpropagation).
    for ep in range(EPOCHS):
        h_pre = X @ W1.T + b1
        h = relu(h_pre)
        pred = h @ W2.T + b2
        err = pred - Y
        loss = np.mean(err ** 2)

        g_pred = (2.0 / N) * err
        gW2 = g_pred.T @ h
        gb2 = g_pred.sum(0)
        g_h = g_pred @ W2
        g_h[h_pre <= 0] = 0.0
        gW1 = g_h.T @ X
        gb1 = g_h.sum(0)

        W2 -= LR * gW2
        b2 -= LR * gb2
        W1 -= LR * gW1
        b1 -= LR * gb1
        if ep % 1000 == 0:
            print(f"epoch {ep:4d}  loss={loss:.6f}")
    print(f"final loss={loss:.6f}")

    # Reference states for verification (float32 to match Rust f32).
    refs_in = X[:3].astype(np.float32)
    h = relu(refs_in @ W1.T.astype(np.float32) + b1)
    refs_out = (h @ W2.T.astype(np.float32) + b2).astype(np.float32)

    emit(W1, b1, W2, b2, refs_in, refs_out)


def fa(x):
    """Format an f32 value with sufficient precision for Rust."""
    return f"{np.float32(x):.8e}"


def mat(name, m, rows_t, cols):
    rows = []
    for r in m:
        rows.append("    [" + ", ".join(fa(v) for v in r) + "],")
    body = "\n".join(rows)
    return f"pub const {name}: [[f32; {cols}]; {rows_t}] = [\n{body}\n];\n"


def vec(name, v):
    return f"pub const {name}: [f32; {len(v)}] = [" + ", ".join(fa(x) for x in v) + "];\n"


def emit(W1, b1, W2, b2, refs_in, refs_out):
    out = os.path.join(os.path.dirname(__file__), "..",
                       "components", "policy", "src", "weights.rs")
    out = os.path.abspath(out)
    with open(out, "w") as f:
        # Generated file: allow excess numeric precision (raw f32 weights).
        f.write("#![allow(clippy::excessive_precision)]\n\n")
        f.write("// Auto-generated by training/train_policy.py — do not edit manually.\n")
        f.write("// MLP weights trained on host, runs no_std on seL4.\n\n")
        f.write(f"pub const IN: usize = {IN};\n")
        f.write(f"pub const HID: usize = {HID};\n")
        f.write(f"pub const OUT: usize = {OUT};\n\n")
        f.write(mat("W1", W1, HID, IN))
        f.write(vec("B1", b1))
        f.write("\n")
        f.write(mat("W2", W2, OUT, HID))
        f.write(vec("B2", b2))
        f.write("\n// Reference states (SIL): Rust inference must match these.\n")
        f.write(mat("REF_IN", refs_in, 3, IN))
        f.write(mat("REF_OUT", refs_out, 3, OUT))
    # Format the generated file so it passes `cargo fmt --check`.
    try:
        import subprocess  # nosec B404  # fixed command, no user input

        subprocess.run(["rustfmt", "--edition", "2021", out], check=False)  # nosec B603 B607
    except FileNotFoundError:
        pass
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
