#!/usr/bin/env python3
"""Train a small perceptual encoder on the host and export its weights as Rust consts (no_std).

Concept: an 8×8 "image" → embedding of length 16 that enters the neural memory. We train the encoder
(via a classification head) so that patterns from the same class produce similar embeddings (high cosine),
allowing the robot to recognise a pattern despite noise — via similarity rather than exact matching.

Output: components/perception/src/weights.rs
"""
import os
import subprocess  # nosec B404  # fixed command (rustfmt), no user input
import numpy as np

np.random.seed(11)

SIDE = 8
FRAME = SIDE * SIDE      # 64
EMB = 16
CLASSES = 4
N = 800
EPOCHS = 3000
LR = 0.08
NOISE = 0.25


def prototype(cls):
    img = np.zeros((SIDE, SIDE), np.float32)
    if cls == 0:                      # vertical stripe
        img[:, 3:5] = 1.0
    elif cls == 1:                    # horizontal stripe
        img[3:5, :] = 1.0
    elif cls == 2:                    # diagonal
        for i in range(SIDE):
            img[i, i] = 1.0
    else:                            # frame (border)
        img[0, :] = img[SIDE - 1, :] = 1.0
        img[:, 0] = img[:, SIDE - 1] = 1.0
    return img.reshape(-1)


def relu(x):
    return np.maximum(x, 0.0)


def main():
    protos = np.stack([prototype(c) for c in range(CLASSES)]).astype(np.float32)

    # Training data: noisy samples of each class.
    X = np.zeros((N, FRAME), np.float32)
    y = np.zeros((N, CLASSES), np.float32)
    for n in range(N):
        c = n % CLASSES
        X[n] = np.clip(protos[c] + np.random.randn(FRAME).astype(np.float32) * NOISE, 0, 1)
        y[n, c] = 1.0

    # encoder: FRAME→EMB (ReLU); head: EMB→CLASSES (training only).
    We = (np.random.randn(EMB, FRAME) * 0.15).astype(np.float32)
    be = np.zeros(EMB, np.float32)
    Wh = (np.random.randn(CLASSES, EMB) * 0.3).astype(np.float32)
    bh = np.zeros(CLASSES, np.float32)

    for ep in range(EPOCHS):
        z1 = X @ We.T + be
        emb = relu(z1)
        logits = emb @ Wh.T + bh
        err = logits - y
        loss = np.mean(err ** 2)

        g_logits = (2.0 / N) * err
        gWh = g_logits.T @ emb
        gbh = g_logits.sum(0)
        g_emb = g_logits @ Wh
        g_z1 = g_emb * (z1 > 0)
        gWe = g_z1.T @ X
        gbe = g_z1.sum(0)

        Wh -= LR * gWh
        bh -= LR * gbh
        We -= LR * gWe
        be -= LR * gbe
        if ep % 1000 == 0:
            acc = (logits.argmax(1) == y.argmax(1)).mean()
            print(f"epoch {ep:4d} loss={loss:.5f} acc={acc:.3f}")
    print(f"final loss={loss:.5f} acc={(logits.argmax(1)==y.argmax(1)).mean():.3f}")

    def encode(frame):
        return relu(frame.astype(np.float32) @ We.T.astype(np.float32) + be).astype(np.float32)

    def cos(a, b):
        return float(a @ b / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-8))

    # Clustering verification: noisy-class2 is closer to prototype-class2 than to any other class.
    query = np.clip(protos[2] + np.random.randn(FRAME).astype(np.float32) * NOISE, 0, 1).astype(np.float32)
    eq = encode(query)
    sims = [cos(eq, encode(protos[c])) for c in range(CLASSES)]
    print("query(class2) cosine to each prototype:", [f"{s:.3f}" for s in sims])
    if int(np.argmax(sims)) != 2:
        raise RuntimeError("encoder clustering failed (query not closest to class 2)")

    ref_emb = np.stack([encode(protos[c]) for c in range(3)]).astype(np.float32)
    emit(We, be, protos, query, ref_emb)


def fa(x):
    return f"{np.float32(x):.8e}"


def mat(name, m, rows, cols):
    body = "\n".join("    [" + ", ".join(fa(v) for v in r) + "]," for r in m)
    return f"pub const {name}: [[f32; {cols}]; {rows}] = [\n{body}\n];\n"


def vec(name, v):
    return f"pub const {name}: [f32; {len(v)}] = [" + ", ".join(fa(x) for x in v) + "];\n"


def emit(We, be, protos, query, ref_emb):
    out = os.path.abspath(os.path.join(os.path.dirname(__file__), "..",
                                       "components", "perception", "src", "weights.rs"))
    with open(out, "w") as f:
        f.write("#![allow(clippy::excessive_precision)]\n\n")
        f.write("// Auto-generated by training/train_encoder.py — do not edit manually.\n")
        f.write("// Perceptual encoder trained on host, runs no_std on seL4.\n\n")
        f.write(f"pub const FRAME: usize = {FRAME};\n")
        f.write(f"pub const EMB: usize = {EMB};\n")
        f.write(f"pub const CLASSES: usize = {CLASSES};\n\n")
        f.write(mat("WE", We, EMB, FRAME))
        f.write(vec("BE", be))
        f.write("\n// Clean reference patterns (one class per row) + noisy query (class 2).\n")
        f.write(mat("CLEAN_FRAMES", protos, CLASSES, FRAME))
        f.write(vec("QUERY_FRAME", query))
        f.write("pub const QUERY_CLASS: usize = 2;\n\n")
        f.write("// Reference embeddings (SIL): Rust inference must match these.\n")
        f.write(mat("REF_EMB", ref_emb, 3, EMB))
    try:
        subprocess.run(["rustfmt", "--edition", "2021", out], check=False)  # nosec B603 B607
    except FileNotFoundError:
        pass
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
