#!/usr/bin/env python3
"""Train a neural (MLP) policy to balance the cart-pole and export it no_std for seL4.

Behavioural cloning: generate data from a working PD controller (state → command), then train an MLP
(4→32→1) to learn the control function. At runtime: network output → safety layer → force.
Demonstrates: train on host, run identical inference on seL4 (SIL).

Output: components/cartpole-policy/src/weights.rs
"""
import os
import subprocess  # nosec B404  # fixed command (rustfmt), no user input

import numpy as np

np.random.seed(21)

IN, HID, OUT = 4, 32, 1

# Physics matching sim/sil-cartpole (and Gym CartPole).
G, M_CART, M_POLE, LEN, FORCE_MAG, DT = 9.8, 1.0, 0.1, 0.5, 10.0, 0.02


def cp_step(s, force):
    x, x_dot, th, th_dot = s
    total = M_CART + M_POLE
    pml = M_POLE * LEN
    sin, cos = np.sin(th), np.cos(th)
    temp = (force + pml * th_dot * th_dot * sin) / total
    th_acc = (G * sin - cos * temp) / (LEN * (4.0 / 3.0 - M_POLE * cos * cos / total))
    x_acc = temp - pml * th_acc * cos / total
    return np.array([x + DT * x_dot, x_dot + DT * x_acc,
                     th + DT * th_dot, th_dot + DT * th_acc], np.float32)


def pd_command(s):
    # Strong cart centering (x, x_dot) to prevent drift after disturbances, while keeping pole balanced.
    x, x_dot, th, th_dot = s
    return (40.0 * th + 9.0 * th_dot + 2.0 * x + 3.2 * x_dot) / FORCE_MAG


def relu(z):
    return np.maximum(z, 0.0)


def main():
    # Generate data: trajectories with random initial states and random impulses, under the PD controller.
    xs, ys = [], []
    for _ in range(120):
        s = np.array([0.0, 0.0, np.random.uniform(-0.1, 0.1), 0.0], np.float32)
        for k in range(400):
            if np.random.rand() < 0.01:
                s[3] += np.random.uniform(-1.8, 1.8)
            cmd = pd_command(s)
            xs.append(s.copy())
            ys.append([cmd])
            s = cp_step(s, float(np.clip(cmd, -1, 1)) * FORCE_MAG)
            if abs(s[2]) > 0.6:
                break
    X = np.array(xs, np.float32)
    Y = np.array(ys, np.float32)
    print(f"samples: {len(X)}")

    # MLP 4→32→1, SGD training (MSE).
    W1 = (np.random.randn(HID, IN) * 0.3).astype(np.float32)
    b1 = np.zeros(HID, np.float32)
    W2 = (np.random.randn(OUT, HID) * 0.3).astype(np.float32)
    b2 = np.zeros(OUT, np.float32)
    n = len(X)
    lr = 0.02
    for ep in range(6000):
        z1 = X @ W1.T + b1
        h = relu(z1)
        pred = h @ W2.T + b2
        err = pred - Y
        loss = np.mean(err ** 2)
        g = (2.0 / n) * err
        gW2 = g.T @ h
        gb2 = g.sum(0)
        gh = g @ W2
        gh[z1 <= 0] = 0.0
        gW1 = gh.T @ X
        gb1 = gh.sum(0)
        W2 -= lr * gW2
        b2 -= lr * gb2
        W1 -= lr * gW1
        b1 -= lr * gb1
        if ep % 1500 == 0:
            print(f"epoch {ep:4d} loss={loss:.5f}")
    print(f"final loss={loss:.5f}")

    refs_in = X[:3].astype(np.float32)
    refs_out = (relu(refs_in @ W1.T + b1) @ W2.T + b2).astype(np.float32)
    emit(W1, b1, W2, b2, refs_in, refs_out)


def fa(v):
    return f"{np.float32(v):.8e}"


def mat(name, m, rows, cols):
    body = "\n".join("    [" + ", ".join(fa(v) for v in r) + "]," for r in m)
    return f"pub const {name}: [[f32; {cols}]; {rows}] = [\n{body}\n];\n"


def vec(name, v):
    return f"pub const {name}: [f32; {len(v)}] = [" + ", ".join(fa(x) for x in v) + "];\n"


def emit(W1, b1, W2, b2, refs_in, refs_out):
    out = os.path.abspath(os.path.join(os.path.dirname(__file__), "..",
                                       "components", "cartpole-policy", "src", "weights.rs"))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("#![allow(clippy::excessive_precision)]\n\n")
        f.write("// Auto-generated by training/train_cartpole.py — do not edit manually.\n")
        f.write("// Cart-pole balancing policy trained on host, runs no_std on seL4.\n\n")
        f.write(f"pub const IN: usize = {IN};\n")
        f.write(f"pub const HID: usize = {HID};\n")
        f.write(f"pub const OUT: usize = {OUT};\n\n")
        f.write(mat("W1", W1, HID, IN))
        f.write(vec("B1", b1))
        f.write("\n")
        f.write(mat("W2", W2, OUT, HID))
        f.write(vec("B2", b2))
        f.write("\n// Reference states (SIL).\n")
        f.write(mat("REF_IN", refs_in, 3, IN))
        f.write(mat("REF_OUT", refs_out, 3, OUT))
    try:
        subprocess.run(["rustfmt", "--edition", "2021", out], check=False)  # nosec B603 B607
    except FileNotFoundError:
        pass
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
