#!/usr/bin/env python3
"""Train a walker (Walker2d) with real PPO on MuJoCo physics and export its policy no_std for seL4.

Step B-1: from balancing a pendulum → learning to **walk** (a foundational motor skill, like a child).
Real reinforcement learning (PPO, stable-baselines3). We export the actor network
(17→64→64→6, tanh) as Rust no_std weights.

Output: components/walker-policy/src/weights.rs  +  ~/Desktop/mujoco-walker.gif
Usage: train_walker.py [total_timesteps]
"""
import os
import sys

os.environ.setdefault("MUJOCO_GL", "egl")
import gymnasium as gym  # noqa: E402
import numpy as np  # noqa: E402
from stable_baselines3 import PPO  # noqa: E402
from stable_baselines3.common.env_util import make_vec_env  # noqa: E402

ENV = "Walker2d-v5"
STEPS = int(sys.argv[1]) if len(sys.argv) > 1 else 800_000


def main():
    venv = make_vec_env(ENV, n_envs=4)
    # Reasonable PPO hyperparameters for locomotion (rl-zoo-style).
    model = PPO(
        "MlpPolicy", venv, verbose=1, n_steps=2048, batch_size=64, n_epochs=10,
        gamma=0.99, gae_lambda=0.95, clip_range=0.2, ent_coef=0.0, learning_rate=3e-4,
        policy_kwargs=dict(net_arch=[64, 64]),
    )
    print(f"training PPO on {ENV} for {STEPS} steps (4 parallel envs)...")
    model.learn(total_timesteps=STEPS, progress_bar=False)
    mdir = os.path.join(os.path.dirname(__file__), "..", "tools", "models")
    os.makedirs(mdir, exist_ok=True)
    model.save(os.path.join(mdir, "walker"))  # for live viewing later

    # Evaluation: mean return (distance covered without falling).
    ev = gym.make(ENV)
    rewards = []
    for ep in range(5):
        obs, _ = ev.reset(seed=ep)
        tot, done = 0.0, False
        while not done:
            a, _ = model.predict(obs, deterministic=True)
            obs, r, term, trunc, _ = ev.step(a)
            tot += r
            done = term or trunc
        rewards.append(tot)
    print(f"EVAL mean_reward={np.mean(rewards):.0f} +/- {np.std(rewards):.0f}  (Walker2d 'walks' ~>2000)")

    render_gif(model)
    export_policy(model)


def render_gif(model):
    try:
        import imageio.v2 as imageio
        env = gym.make(ENV, render_mode="rgb_array")
        obs, _ = env.reset(seed=0)
        frames = []
        for _ in range(400):
            frames.append(env.render())
            a, _ = model.predict(obs, deterministic=True)
            obs, _, term, trunc, _ = env.step(a)
            if term or trunc:
                obs, _ = env.reset()
        out = os.path.expanduser("~/Desktop/mujoco-walker.gif")
        imageio.mimsave(out, frames, fps=30)
        print(f"rendered walking robot: {out}")
    except Exception as e:  # noqa: BLE001
        print(f"(render skipped: {e})", file=sys.stderr)


def export_policy(model):
    """Extract the deterministic actor network (obs→mean) and export it no_std."""
    import torch
    pol = model.policy
    pn = pol.mlp_extractor.policy_net  # Sequential(Linear,Tanh,Linear,Tanh)
    w0, b0 = pn[0].weight.detach().numpy(), pn[0].bias.detach().numpy()
    w1, b1 = pn[2].weight.detach().numpy(), pn[2].bias.detach().numpy()
    wa, ba = pol.action_net.weight.detach().numpy(), pol.action_net.bias.detach().numpy()

    # Reference states (SIL): pass through torch to fix the match.
    refs = np.array([
        [0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.2, 0.1, -0.1, 0.05, 0.0, 0.1, -0.05, 0.0, 0.3, -0.2, 0.1, 0.0, 0.0, -0.1, 0.0, 0.05, 0.0],
        [-0.1, 0.05, 0.2, -0.1, 0.1, 0.0, 0.0, 0.1, -0.1, 0.2, 0.0, -0.1, 0.05, 0.0, 0.1, 0.0, -0.05],
    ], np.float32)
    with torch.no_grad():
        h = pol.mlp_extractor.policy_net(torch.tensor(refs))
        ref_out = pol.action_net(h).numpy().astype(np.float32)

    n_in, h1, h2, n_out = w0.shape[1], w0.shape[0], w1.shape[0], wa.shape[0]
    out = os.path.abspath(os.path.join(os.path.dirname(__file__), "..",
                                       "components", "walker-policy", "src", "weights.rs"))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("#![allow(clippy::excessive_precision, clippy::large_const_arrays)]\n\n")
        f.write("// Auto-generated by training/train_walker.py — do not edit manually.\n")
        f.write("// Walking policy (PPO on MuJoCo Walker2d), no_std inference on seL4. tanh between layers.\n\n")
        f.write(f"pub const IN: usize = {n_in};\npub const H1: usize = {h1};\n")
        f.write(f"pub const H2: usize = {h2};\npub const OUT: usize = {n_out};\n\n")
        for nm, m in [("W0", w0), ("W1", w1), ("WA", wa)]:
            f.write(mat(nm, m))
            f.write(vec(nm.replace("W", "B"), {"W0": b0, "W1": b1, "WA": ba}[nm]))
            f.write("\n")
        f.write("// Reference states (SIL).\n")
        f.write(mat("REF_IN", refs))
        f.write(mat("REF_OUT", ref_out))
    print(f"wrote {out}  ({n_in}->{h1}->{h2}->{n_out})")


def fa(v):
    return f"{np.float32(v):.8e}"


def mat(name, m):
    rows, cols = m.shape
    body = "\n".join("    [" + ", ".join(fa(v) for v in r) + "]," for r in m)
    return f"pub const {name}: [[f32; {cols}]; {rows}] = [\n{body}\n];\n"


def vec(name, v):
    return f"pub const {name}: [f32; {len(v)}] = [" + ", ".join(fa(x) for x in v) + "];\n"


if __name__ == "__main__":
    main()
