#!/usr/bin/env python3
"""Train a humanoid (Humanoid) with PPO on MuJoCo — step B-2 (standing/walking like a child).

Honest: Humanoid is much harder than Walker (obs=348, action=17), and PPO on CPU with a limited budget
typically learns to stand/balance/take first steps rather than strong walking (needs GPU + many more steps).
Output: components/humanoid-policy/src/weights.rs + ~/Desktop/mujoco-humanoid.gif
Usage: train_humanoid.py [steps]
"""
import os
import sys

os.environ.setdefault("MUJOCO_GL", "egl")
import gymnasium as gym  # noqa: E402
import numpy as np  # noqa: E402
import torch  # noqa: E402
from stable_baselines3 import PPO  # noqa: E402
from stable_baselines3.common.env_util import make_vec_env  # noqa: E402

ENV = "Humanoid-v5"
STEPS = int(sys.argv[1]) if len(sys.argv) > 1 else 1_500_000


def main():
    venv = make_vec_env(ENV, n_envs=8)
    model = PPO(
        "MlpPolicy", venv, verbose=1, n_steps=2048, batch_size=256, n_epochs=10,
        gamma=0.99, gae_lambda=0.95, clip_range=0.2, ent_coef=0.0, learning_rate=3e-4,
        policy_kwargs=dict(net_arch=[256, 256]),
    )
    print(f"training PPO on {ENV} for {STEPS} steps (8 envs)...")
    model.learn(total_timesteps=STEPS, progress_bar=False)
    mdir = os.path.join(os.path.dirname(__file__), "..", "tools", "models")
    os.makedirs(mdir, exist_ok=True)
    model.save(os.path.join(mdir, "humanoid"))  # for live viewing later

    ev = gym.make(ENV)
    rewards = []
    for ep in range(5):
        obs, _ = ev.reset(seed=ep)
        tot, done = 0.0, False
        while not done:
            a, _ = model.predict(obs, deterministic=True)
            obs, r, term, trunc, _ = ev.step(a)
            tot += r
            done = term or trunc
        rewards.append(tot)
    print(f"EVAL mean_reward={np.mean(rewards):.0f} +/- {np.std(rewards):.0f}  (Humanoid robust walk ~>5000)")

    render_gif(model)
    export_policy(model)


def render_gif(model):
    try:
        import imageio.v2 as imageio
        env = gym.make(ENV, render_mode="rgb_array")
        obs, _ = env.reset(seed=0)
        frames = []
        for _ in range(400):
            frames.append(env.render())
            a, _ = model.predict(obs, deterministic=True)
            obs, _, term, trunc, _ = env.step(a)
            if term or trunc:
                obs, _ = env.reset()
        out = os.path.expanduser("~/Desktop/mujoco-humanoid.gif")
        imageio.mimsave(out, frames, fps=30)
        print(f"rendered humanoid: {out}")
    except Exception as e:  # noqa: BLE001
        print(f"(render skipped: {e})", file=sys.stderr)


def export_policy(model):
    pol = model.policy
    pn = pol.mlp_extractor.policy_net
    w0, b0 = pn[0].weight.detach().numpy(), pn[0].bias.detach().numpy()
    w1, b1 = pn[2].weight.detach().numpy(), pn[2].bias.detach().numpy()
    wa, ba = pol.action_net.weight.detach().numpy(), pol.action_net.bias.detach().numpy()
    rng = np.random.default_rng(0)
    refs = rng.standard_normal((3, w0.shape[1])).astype(np.float32) * 0.2
    with torch.no_grad():
        h = pol.mlp_extractor.policy_net(torch.tensor(refs))
        ref_out = pol.action_net(h).numpy().astype(np.float32)
    n_in, h1, h2, n_out = w0.shape[1], w0.shape[0], w1.shape[0], wa.shape[0]
    out = os.path.abspath(os.path.join(os.path.dirname(__file__), "..",
                                       "components", "humanoid-policy", "src", "weights.rs"))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("#![allow(clippy::excessive_precision, clippy::large_const_arrays)]\n\n")
        f.write("// Auto-generated by training/train_humanoid.py — do not edit manually.\n")
        f.write("// Humanoid policy (PPO on MuJoCo Humanoid), no_std inference on seL4.\n\n")
        f.write(f"pub const IN: usize = {n_in};\npub const H1: usize = {h1};\n")
        f.write(f"pub const H2: usize = {h2};\npub const OUT: usize = {n_out};\n\n")
        for nm, m, bvec in [("W0", w0, b0), ("W1", w1, b1), ("WA", wa, ba)]:
            f.write(mat(nm, m))
            f.write(vec(nm.replace("W", "B"), bvec))
            f.write("\n")
        f.write("// Reference states (SIL).\n")
        f.write(mat("REF_IN", refs))
        f.write(mat("REF_OUT", ref_out))
    print(f"wrote {out}  ({n_in}->{h1}->{h2}->{n_out})")


def fa(v):
    return f"{np.float32(v):.8e}"


def mat(name, m):
    rows, cols = m.shape
    body = "\n".join("    [" + ", ".join(fa(v) for v in r) + "]," for r in m)
    return f"pub const {name}: [[f32; {cols}]; {rows}] = [\n{body}\n];\n"


def vec(name, v):
    return f"pub const {name}: [f32; {len(v)}] = [" + ", ".join(fa(x) for x in v) + "];\n"


if __name__ == "__main__":
    main()
